version: "3.8"

services:
  web:
    container_name: posts_social_network-web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
    depends_on:
       - db

  db:
    image: postgres
    container_name: posts_social_network-db
    volumes:
      - posts_social_network_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=posts_social_network
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2635
    ports:
      - "5432:5432"

volumes:
  posts_social_network_db:
    external: false
